---
- name: 'Instala pacotes de dependencia do sistema operacional'
  apt:
    name: ['mysql-server-5.6','python-mysqldb']
    state: latest
  become: yes

- name: 'Cria o banco do MySQL'
  mysql_db:
    name: "{{ wp_db_name }}"
    login_user: root
    state: present

- name: 'Cria o usuario do MySQL'
  mysql_user:
    login_user: root
    name: "{{ wp_username }}"
    password: "{{wp_user_password}}"
    priv: "{{ wp_db_name }}.*:ALL"
    state: present
    host: "{{ item }}"
  with_items:
    - 'localhost'
    - '127.0.0.1'
    - "{{wp_host_ip}}"

- name: 'Configura o MySQL para aceitar conexoes remotas'
  copy:
    src: 'files/my.cnf'
    dest: '/etc/mysql/my.cnf'
  become: yes
  notify:
    - restart mysql
